# -*- coding: utf-8 -*-
{
    'name': 'O.FRE.SER',
    'version': '1.0',
    'summary': 'O.FRE.SER',
    'sequence': 1,
    'description': """
O.FRE.SER
======================
    """,
    'category': 'O.FRE.SER',
    'website': 'https://www.ofreser.com.ar/',
    'images': [],
    'author': 'BlackFish-Team',
    'depends': ['website',
                'product',
                'fleet',
                'hr',
                'sale'
                ],
    'data': [
        'data/site_data.xml',
        'data/sequences.xml',
        'data/resources.xml',
        'data/product.xml',
        'data/orden_de_trabajo.xml',
        'security/ofreser_security.xml',
        "wizards/vencimientos_wizard_view.xml",
        "wizards/certificados_wizard_view.xml",
        'wizards/productos_consumidos_wizard_view.xml',
        'views/ofrecer_view.xml',
        'views/product_template_view.xml',
        'views/res_user_view.xml',
        'views_site/archivos_view.xml',
        'views_site/layout.xml',
        'views_site/layout.xml',
        'views_site/orden_de_trabajo_tablero.xml',
        'views_site/orden_de_trabajo_individual.xml',
        'views/orden_de_trabajo_view.xml',
        'views/maquina_view.xml',
        'views/rubro_view.xml',
        'views/tipo_de_trabajo_view.xml',
        'views/liquidacion_view.xml',
        'views/certificados_view.xml',
        'views/fleet_view.xml',
        "views/configuraciones.xml",
        'views/hr_employee_view.xml',
        "views/res_partner.xml",        
        "reports/liquidacion_en_lote_report.xml",
        "reports/liquidacion_en_lote_template.xml",
        "reports/vencimientos_report.xml",
        "reports/vencimientos_template.xml",
        'reports/producto_consumido_report.xml',
        'reports/producto_consumido_template.xml',
        'security/ir.model.access.csv',
    ],
    'demo': [
        # 'demo/base_demo.xml',
    ],
    'qweb': [
        # "static/src/xml/account_reconciliation.xml",
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    # 'post_init_hook': '_auto_install_l10n',
}
