from . import res_users
from . import maquina
from . import orden_de_trabajo
from . import producto_consumido
from . import rubro
from . import tipo_de_trabajo
from . import mano_de_obra_utilizada
from . import maquinas_utilizadas
from . import promotores
from . import porcentajes_extras
from . import movilidad_utilizadas
from . import liquidacion
from . import mano_de_obra_liquidacion
from . import fleet
from . import res_partner
from . import certificados
from . import hr_employee
