from . import res_users
import maquina
import orden_de_trabajo
import producto_consumido
import rubro
import tipo_de_trabajo
import mano_de_obra_utilizada
import maquinas_utilizadas
import promotores
import porcentajes_extras
import movilidad_utilizadas
import liquidacion
import mano_de_obra_liquidacion
import fleet
import res_partner
import certificados
import hr_employee
